Repository aws-quickstart/quickstart-vmware-tanzu-application-platform, pull requests merged in 2022-10, with the labels that each got.

#110 Modified decription for TanzuNetRelocatImages
  templates/aws-tap-entrypoint-existing-vpc.template.yaml
  templates/aws-tap-entrypoint-new-vpc.template.yaml
Labels: documentation

#114 Updated the windows ami for us-east-1
  templates/aws-tap-entrypoint-existing-vpc.template.yaml
Labels: bug

#113 Moved about TANZU link
  docs/deployment_guide/partner_editable/licenses.adoc
  docs/deployment_guide/partner_editable/overview.adoc
Labels: documentation

#116 TAP 1.3.0 release updates
  tap-setup-scripts/src/functions.sh
  tap-setup-scripts/src/inputs/tap-values.yaml
  tap-setup-scripts/src/inputs/user-input-values.example.yaml
  tap-setup-scripts/src/resources/developer-namespace.yaml
  tap-setup-scripts/src/resources/metadata-store-ready-only.yaml
  tap-setup-scripts/src/resources/scan-policy.yaml
  templates/aws-tap-entrypoint-existing-vpc.template.yaml
  templates/aws-tap-entrypoint-new-vpc.template.yaml
Labels: enhancement
